FROM node:16-alpine3.12
WORKDIR /www/coup/
COPY . .

# Set environment variables

ENV NODE_ENV DEV
ENV NEXT_PUBLIC_HOST localhost
RUN npm config set registry http://registry.npm.taobao.org/
# RUN yarn config set registry https://registry.npm.taobao.org/
RUN npm install
# RUN npm run build
EXPOSE 3000
CMD [ "npm", "run", "dev" ]
