export enum OP_CODE {
    UNCODE = 0,
    START = 1,
    DRAW_CARD = 2,
    DISCARD_CARD = 3,
    DRAW_COINS = 4,
    QUESTION = 5,
    DONE = 6,
    STEAL_COINS = 7,
    CHANGE_CARD = 8,
    ASSASSIN = 9,
    DRAW_THREE_COINS = 10,
    DENY_STEAL = 11,
    DENY_KILL = 12,
    DENY_MONEY = 13,
    COUP = 14,
    READY_START = 15,
    UPDATE = 16,
    REJECTED = 17,
    CHOOSE_CARD = 18,
    INFO = 19,
    TICK = 20,
    DEAD = 21,
}
