export enum OP_CODE {
    UNCODE = 0,
    START = 1,
    DRAW_CARD = 2,
    DISCARD_CARD = 3,
    DRAW_COIN = 4,
    QUESTION = 5,
    DONE = 6,
    STEAL_COINS = 7,
    CHANGE_CARD = 8,
    ASSASSIN = 9,
    DRAW_THREE_COINS = 10,
    DENY_STEAL = 11,
    DENY_KILL = 12,
    COUP = 13,
    DRAW_TWO_COINS = 14,
    DENY_TWO_COINS = 15,
}
